config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", :locale => /en|fr/ do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'forum/index'

  get 'forum/show'

  get 'forum/sujet'
	post '/anime/aime/:id' => 'geek#aime'
post '/jeux/aime/:id' => 'jeux#aime'
post '/serie/aime/:id' => 'serie#aime'
  root 'tweets#index'
  get '/sujet/:id'=>'forum#sujet'
    get '/freche'=>'forum#reche'
      post '/freche'=>'forum#reche'
  get 'geek/animer'
  get 'forumshow/:id'=>'forum#show'
  get 'forum' =>'forum#index'
  post 'addsouscat'=>'forum#addsouscat'
    post 'createpost'=>'forum#createpost'
  resources :animers
post 'serie/createcom'
post 'geek/createcom'
post 'jeux/createcom'
  get 'users/user'
  get 'users/log'
  get 'addanime'=>'geek#addanime'
    get 'anime/:id'=>'geek#unanime'
    get 'arendom'=>'geek#aleatoirea'
      get 'arechegenre'=>'geek#arechegenre'
      post 'arechegenre'=>'geek#arechegenre'
  post 'save'=>'geek#save'
  patch 'update' =>'users#up'
get 'chats' =>'home#index'
get 'addmessage'=>'tweets#addmessage'
post 'mesot'=>'tweets#meso'
#route pour les jeux
post 'jcreate' =>'jeux#jcreate'
get 'addjeux' =>'jeux#addjeux'
get 'lesjeux' =>'jeux#lesjeux'
get 'jeuxt' =>'jeux#jeux'
get 'jeux/:id'=>'jeux#unjeux'
get 'aleatoirej'=>'jeux#aleatoirej'
  get 'jrechegenre'=>'jeux#jrechegenre'
   post 'jrechegenre'=>'jeux#jrechegenre'
post '/jreche' =>'jeux#reche'
#route pour les serie
post 'screate' =>'serie#screate'
get 'addserie' =>'serie#addserie'
get 'lesseries' =>'serie#lesseries'
get 'seriet' =>'serie#serie'
get 'serie/:id'=>'serie#uneserie'
get 'aleatoires'=>'serie#aleatoires'
  get 'srechegenre'=>'serie#srechegenre'
   post 'srechegenre'=>'serie#srechegenre'
post '/sreche' =>'serie#reche'
#
post 'users/connection' => 'users#connection'
  get 'users/log' => 'users#log'
    get 'users/amis' => 'users#amis'
      get 'users/profil/:id/:pt'=> 'users#profil'
post' animers_path' =>'users#animers_path'
get 'users/deco' => 'users#deco'
resources :photos, only: [:new, :create, :index]
get 'show/:id' => 'tweets#show'
get 'tweeta' => 'tweets#tweeta'
get 'follow' => 'tweets#follow'
get '/tweets/convers' => 'tweets#convers'

get '/setvaluedb' => 'tweets#setvaluedb'
get '/optmessage' => 'tweets#optmessage'
  post 'users/tweet' => 'users#login'
post '/followers/:id' => 'tweets#followers'
post 'tweets/createa' => 'tweets#createa'
post 'createcom' => 'tweets#createcom'
post 'aime/:id' => "tweets#aime"
post 'aime2/:id' => "tweets#aime2"
post '/updat' =>'users#updat'
post '/reche' =>'users#reche'
get '/reche' =>'users#reche'
post '/areche' =>'geek#reche'
get '/lesanimes' =>'geek#lesanimes'
get '/chat' =>'users#chat'
get '/show' =>'users#show'
post '/demande/:id' =>'users#demande'
post '/acc/:id' =>'users#accept'
post '/sup/:id' =>'users#supr'
end
resources :tweets

  devise_for :users

  resources :conversations, only: [:create] do
    member do
      post :close
    end

    resources :messages, only: [:create]
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/alike.rb
class Alike < ActiveRecord::Base


end

app/models/ami.rb
class Ami < ActiveRecord::Base


end

app/models/animer.rb
class Animer < ActiveRecord::Base
has_many :categorieas
has_many :listegenres
dragonfly_accessor :image
end

app/models/categoriea.rb
class Categoriea < ActiveRecord::Base

  belongs_to :animer
  has_many :listegenre
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
 # belongs_to :sender, foreign_key: :sender_id, class_name: User
#  belongs_to :recipient, foreign_key: :recipient_id, class_name: User

  validates :sender_id, uniqueness: { scope: :recipient_id }

  scope :between, -> (sender_id, recipient_id) do
    where(sender_id: sender_id, recipient_id: recipient_id).or(
      where(sender_id: recipient_id, recipient_id: sender_id)
    )
  end

  def self.get(sender_id, recipient_id)
    conversation = between(sender_id, recipient_id).first
    return conversation if conversation.present?

    create(sender_id: sender_id, recipient_id: recipient_id)
  end

  def opposed_user(user)
    user == recipient_id ? sender_id : recipient_id
  end
end

app/models/demande.rb
class Demande < ActiveRecord::Base


end

app/models/dlike.rb
class Dlike < ActiveRecord::Base


end

app/models/follower.rb
class Follower < ActiveRecord::Base


end

app/models/jeux.rb
class Jeux < ActiveRecord::Base
has_many :categoriejeuxs
has_many :jeuxgenres
dragonfly_accessor :image
end

app/models/jeuxgenre.rb
class Jeuxgenre< ActiveRecord::Base
  belongs_to :categoriejeux
    belongs_to :jeux

end

app/models/jlike.rb
class Jlike < ActiveRecord::Base


end

app/models/listegenre.rb
class Listegenre< ActiveRecord::Base
  belongs_to :categoriea
    belongs_to :animer

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  


end

app/models/photo.rb
class Photo < ApplicationRecord
  dragonfly_accessor :image
end

app/models/post.rb
class Post< ActiveRecord::Base

    belongs_to :user
  dragonfly_accessor :image
end

app/models/serie.rb
class Serie < ActiveRecord::Base
has_many :categorieserie
has_many :seriegenres
dragonfly_accessor :image
end

app/models/setdbdata.rb
class Setdbdata < ApplicationRecord
    self.table_name = 'setdbdatas'
  


end

app/models/slike.rb
class Slike < ActiveRecord::Base


end

app/models/tweet.rb
class Tweet < ApplicationRecord
  dragonfly_accessor :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :souscatforms
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  
end

app/views/conversations/_conversation.html.erb
<div class="fixedu tmess"><li>
  <div class="panel2 panel-default" data-conversation-id="<%= conversation.id %>">

    <div class="panel-heading2"  id="converet<%=conversation.id%>">
    <%id =user.id == conversation.recipient_id ? conversation.sender_id : conversation.recipient_id%>
        <%= link_to image_tag(Photo.where(user:  id).last.image.thumb('30x30#').url, alt: user.id, class: 'img-thumbnail')%>
      <%= link_to User.find(id).pseudo, '', class: 'toggle-window' %>
      <%= link_to "x", close_conversation_path(conversation), class: "btn btn-default btn-xs pull-right", remote: true, method: :post %>
    </div>

    <script type="text/javascript">

      $(document).ready(function(e) {

        $('#input_default_<%=conversation.id %>').emojiPicker({

      height: '200px'
    });



      // keyup event is fired
        $(".emojiable-question, .emojiable-option").on("keyup", function () {
          //console.log("emoji added, input val() is: " + $(this).val());
        });

      });
    </script>

    <div class="panel-body" id="con<%=conversation.id%>">
      <div class="messages-list " id ="preview<%=conversation.id %>" >
        <ul>
          <%= render 'conversations/conversation_content', messages: conversation.messages, user: user %>
        </ul>
      </div>

      <%= form_tag "/addmessage", method: "post" do %>

        <input name="conversation_id" type="hidden" value="<%= conversation.id %>">
        <input name="user_id" type="hidden" value="<%= user.id %>">
          <input name="opoeduser_id" type="hidden" value="<%= User.find(id).pseudo %>">
        <textarea name="cont" class="form-control input " id="input_default_<%=conversation.id %>"></textarea>
        <input type="hidden" name="body" value="" id="cont<%=conversation.id %>">
        <input type="submit" class="submit2" value="Envoyer" id="sub<%= conversation.id %>" onclick="sendmees<%=conversation.id %>(<%= conversation.id %>);">
      <%end%>

    </div>
  </divs>

<script>

  function sendmees<%=conversation.id %>(id)
  {
;
        document.getElementById("cont<%=conversation.id %>").value=  document.getElementById("input_default_<%=conversation.id %>").value
      document.getElementById("preview<%=conversation.id %>").innerHTML+='<li>    <div class="row">  <div class="message-sent">    '+
      document.getElementById("input_default_<%=conversation.id %>").value
      +'  </div>  </div></li>'
    document.getElementById("input_default_<%=conversation.id %>").value="";
  }
  document.getElementById("con<%= conversation.id %>").style.height="0px";
    document.getElementById("con<%= conversation.id %>").style.visibility="hidden";

document.getElementById("converet<%= conversation.id %>").addEventListener("click", function(){  document.getElementById("input_default_<%=conversation.id %>").value

  if(document.getElementById("con<%= conversation.id %>").style.visibility!="visible")
  {
    document.getElementById("con<%= conversation.id %>").style.height="340px";  document.getElementById("input_default_<%=conversation.id %>").value
      document.getElementById("con<%= conversation.id %>").style.visibility="visible";
  }
  else
  {
    document.getElementById("con<%= conversation.id %>").style.height="0px";
      document.getElementById("con<%= conversation.id %>").style.visibility="hidden";
  }


});
</script>
  <script type="text/javascript">

  </script>
</li>
</div>

app/views/conversations/_conversation_content.html.erb
<% messages.each do |message| %>
  <%= render message, user: user %>
<% end %>

app/views/conversations/close.js.erb
$('#conversations-list').find("[data-conversation-id='" + "<%= @conversation.id %>" + "']").parent().remove();

app/views/conversations/create.js.erb
var conversations = $('#conversations-list');
var conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");

if (conversation.length !== 1) {
  conversations.append("<%= j(render 'conversations/conversation', conversation: @conversation, user: current_user) %>");
  conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
}

conversation.find('.panel-body').show();

var messages_list = conversation.find('.messages-list');
var height = messages_list[0].scrollHeight;
messages_list.scrollTop(height);