config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", :locale => /en|fr/ do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'forum/index'

  get 'forum/show'

  get 'forum/sujet'
	post '/anime/aime/:id' => 'geek#aime'
post '/jeux/aime/:id' => 'jeux#aime'
post '/serie/aime/:id' => 'serie#aime'
  root 'tweets#index'
  get '/sujet/:id'=>'forum#sujet'
    get '/freche'=>'forum#reche'
      post '/freche'=>'forum#reche'
  get 'geek/animer'
  get 'forumshow/:id'=>'forum#show'
  get 'forum' =>'forum#index'
  post 'addsouscat'=>'forum#addsouscat'
    post 'createpost'=>'forum#createpost'
  resources :animers
post 'serie/createcom'
post 'geek/createcom'
post 'jeux/createcom'
  get 'users/user'
  get 'users/log'
  get 'addanime'=>'geek#addanime'
    get 'anime/:id'=>'geek#unanime'
    get 'arendom'=>'geek#aleatoirea'
      get 'arechegenre'=>'geek#arechegenre'
      post 'arechegenre'=>'geek#arechegenre'
  post 'save'=>'geek#save'
  patch 'update' =>'users#up'
get 'chats' =>'home#index'
get 'addmessage'=>'tweets#addmessage'
post 'mesot'=>'tweets#meso'
#route pour les jeux
post 'jcreate' =>'jeux#jcreate'
get 'addjeux' =>'jeux#addjeux'
get 'lesjeux' =>'jeux#lesjeux'
get 'jeuxt' =>'jeux#jeux'
get 'jeux/:id'=>'jeux#unjeux'
get 'aleatoirej'=>'jeux#aleatoirej'
  get 'jrechegenre'=>'jeux#jrechegenre'
   post 'jrechegenre'=>'jeux#jrechegenre'
post '/jreche' =>'jeux#reche'
#route pour les serie
post 'screate' =>'serie#screate'
get 'addserie' =>'serie#addserie'
get 'lesseries' =>'serie#lesseries'
get 'seriet' =>'serie#serie'
get 'serie/:id'=>'serie#uneserie'
get 'aleatoires'=>'serie#aleatoires'
  get 'srechegenre'=>'serie#srechegenre'
   post 'srechegenre'=>'serie#srechegenre'
post '/sreche' =>'serie#reche'
#
post 'users/connection' => 'users#connection'
  get 'users/log' => 'users#log'
    get 'users/amis' => 'users#amis'
      get 'users/profil/:id/:pt'=> 'users#profil'
post' animers_path' =>'users#animers_path'
get 'users/deco' => 'users#deco'
resources :photos, only: [:new, :create, :index]
get 'show/:id' => 'tweets#show'
get 'tweeta' => 'tweets#tweeta'
get 'follow' => 'tweets#follow'
get '/tweets/convers' => 'tweets#convers'

get '/setvaluedb' => 'tweets#setvaluedb'
get '/optmessage' => 'tweets#optmessage'
  post 'users/tweet' => 'users#login'
post '/followers/:id' => 'tweets#followers'
post 'tweets/createa' => 'tweets#createa'
post 'createcom' => 'tweets#createcom'
post 'aime/:id' => "tweets#aime"
post 'aime2/:id' => "tweets#aime2"
post '/updat' =>'users#updat'
post '/reche' =>'users#reche'
get '/reche' =>'users#reche'
post '/areche' =>'geek#reche'
get '/lesanimes' =>'geek#lesanimes'
get '/chat' =>'users#chat'
get '/show' =>'users#show'
post '/demande/:id' =>'users#demande'
post '/acc/:id' =>'users#accept'
post '/sup/:id' =>'users#supr'
end
resources :tweets

  devise_for :users

  resources :conversations, only: [:create] do
    member do
      post :close
    end

    resources :messages, only: [:create]
  end

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  dragonfly_accessor :image
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    
   

   
    if current_user
    @tweets = Tweet.all.find_by_sql("SELECT * FROM tweets where typ is null")
      @tweet = Tweet.new
    else
      redirect_to "/users/log"
    end

  end
  def follow
    
   

   
    if current_user
    
    else
      redirect_to "/users/log"
    end

  end
  def meso 
    a =params[:cont];
  end 
  def addmessage
    if Ami.where("id = ? and u1 = ? or u2 = ?",params[:conversation_id], @current_user.id,@current_user.id)
Message.create body: params[:cont] ,user_id: @current_user.id ,conversation_id: params[:conversation_id]
a = Ami.find(params[:conversation_id]);
var='<li>'+
    '<div class="row recending">'+
    
    "<img src='#{Photo.where(user: @current_user.id).last.image.thumb('40x40#').url}'>"+
      "<div class=' message-received'>"+
     
      "  #{params[:cont]}</div>"+
     
    '</div>'+
  '</li>'
ActionCable.server.broadcast "web_notifications_channel-#{params[:conversation_id]}", message: var,idconv: params[:conversation_id] ,user: @current_user.id ,pseudo: @current_user.pseudo, image: Photo.where(user:  @current_user.id).last.image.thumb('40x40#').url ,cont: params[:cont] 
  end
end 
def setvaluedb
  
    if (Setdbdata.where("userid = ? and style = ? ", params[:id] , params[:style] ).last) 
       u = Setdbdata.where("userid = ? and style = ? ", params[:id] , params[:style] ).last
       u.update userid: params[:id] ,style: params[:style] ,value: params[:value]
    else 
      Setdbdata.create userid: params[:id] ,style: params[:style] ,value: params[:value]
    end 
      

    end  
  
    def followers
      if !Follower.where(u1: @current_user.id , u2: params[:id]).last
      Follower.create u1: @current_user.id , u2: params[:id]
      end 

    end 
def optmessage
  if Ami.where("id = ? and u1 = ? or u2 = ?",params[:oka], @current_user.id,@current_user.id)
  @message = Message.where(	conversation_id: params[:oka])
  Message.where(	conversation_id: params[:oka]).update_all(vue: 'o')
  var = ""
  @message.each do |i|
   
    if  @current_user.id == i.user_id
    var+='<li class="colmo">'+
    '<div class="row sendig">'+
   
    
      "<div class=' message-sent'>"+
     
      "  #{i.body}</div>"+
      "<img  src='#{Photo.where(user: i.user_id).last.image.thumb('40x40#').url}'>"+
      
    '</div>'+
    "<span class='messdate'>#{i.created_at.strftime("%d of %B, %Y, %k:%M")}<span><div class='clear'><p></P></div>"+
  '</li>'
  else
    var+='<li class="colmo">'+
    '<div class="row recending">'+
    
    "<img src='#{Photo.where(user: i.user_id).last.image.thumb('40x40#').url}'>"+
      "<div class=' message-received'>"+
     
      "  #{i.body}</div>"+
     
    '</div>'+
    "<span class='messdate2'>#{i.created_at.strftime("%d of %B, %Y, %k:%M")}<span><div class='clear'><p></P></div>"+
  '</li>'
  end
  end 
  render :json => {:ok => var}, :status => :ok
end
end 
def tweeta
  
 
  
  if current_user
  @tweets = Tweet.all
    @tweeta = Tweet.new
  else
    redirect_to "/users/log"
  end
end
def createcom
  @comm = Commentaire.new(comm_params)

  @comm.auteur = current_user.pseudo

  @comm.typ=2
  respond_to do |format|
    if @comm.save
      format.html { redirect_to "/tweeta", notice: 'Tweet was successfully created.' }
      format.json { render :show, status: :created, location: @comm }
    else
      format.html { render :new }
      format.json { render json: @comm.errors, status: :unprocessable_entity }
    end
  end

end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @commentaire=Commentaire.where(idt: params[:id])
    @comm=Commentaire.new
    @twee=Tweet.find(params[:id])
    @users = User.all.where.not(id: current_user)
  
  end
  def createa
    @tweet = Tweet.new(tweet_params)

    @tweet.auteur = current_user.pseudo

    @tweet.typ=2
    @tweet.aime =0
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to "/tweeta", notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end

  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new

  end

  # GET /tweets/1/edit
  def edit
    @tweet =Tweet.new
    @t =Tweet.find(params[:id])
    @users = User.all.where.not(id: current_user)
    
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.auteur = current_user.pseudo
    @tweet.aime =0
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to "/tweets", notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end
  def aime
    tweet = Tweet.find(params[:id])
    tilte = "aime la publication de " + tweet.auteur
    if Dlike.where(iduser: current_user.id , idpub: tweet.id).last!=nil
    elsif Dlike.where(iduser: current_user.id , idpub: tweet.ido).last!=nil
    else
    if tweet.ido ==nil

      aime =tweet.aime + 1
      tweet.update aime: aime
      Dlike.create iduser:current_user.id , idpub: tweet.id
      ido  =tweet.id
  else
     original = Tweet.find(tweet.ido)
     aime =original.aime + 1
     original.update aime: aime
     Dlike.create iduser:current_user.id , idpub: tweet.ido
     ido =tweet.ido
  end
    tweet.update aime: aime

    resu = Tweet.create content: tweet.content ,auteur: current_user.pseudo , tilte: tilte , aime: 0 ,ido: ido
    resu.image = tweet.image
    resu.save
    redirect_to "/tweets"
  end

  end
  def aime2
    tweet = Tweet.find(params[:id])
    tilte = "aime la publication de " + tweet.auteur
    if Dlike.where(iduser: current_user.id , idpub: tweet.id).last!=nil
    elsif Dlike.where(iduser: current_user.id , idpub: tweet.ido).last!=nil
    else
    if tweet.ido ==nil

      aime =tweet.aime + 1
      tweet.update aime: aime
      Dlike.create iduser:current_user.id , idpub: tweet.id
      ido  =tweet.id
  else
     original = Tweet.find(tweet.ido)
     aime =original.aime + 1
     original.update aime: aime
     Dlike.create iduser:current_user.id , idpub: tweet.ido
     ido =tweet.ido
  end
    tweet.update aime: aime

  resu=  Tweet.create content: tweet.content ,auteur: current_user.pseudo , tilte: tilte , aime: 0 ,ido: ido ,typ: 2
  resu.image = tweet.image
  resu.save
    redirect_to "/tweeta"
  end
end
  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:content , :image)
    end
    def comm_params
      params.require(:commentaire).permit(:content , :image ,:idt)
    end
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <%= form.text_area :content, id: :tweet_content, :size=>'117x7' %>
    <%=form.label :Ajouter_une_image%>
      <%= form.file_field  :image%>
  </div>

  <div class="actions ">
    <%= form.submit "Publier"%>
  </div>
<% end %>

app/views/tweets/convers.html.erb
aaa

app/views/tweets/edit.html.erb
  <p id="notice"><%= notice %></p>
  <div class=" conten">
    <div class="box"><div class="boxgeek"> <div class="alea"><h2> 5 Animer aleatoire</h2><p><%= link_to image_tag(@array[1].image.thumb('50x50#').url, alt: @array[1].id, class: 'img-thumbnail')%>       <a href ="/anime/<%=@array[1].id%>">  &nbsp&nbsp&nbsp<%=@array[1].name%></a></P><p><%= link_to image_tag(@array[2].image.thumb('50x50#').url, alt: @array[2].id, class: 'img-thumbnail')%>       <a href ="/anime/<%=@array[2].id%>">  &nbsp&nbsp&nbsp<%=@array[2].name%></a></P><p><%= link_to image_tag(@array[3].image.thumb('50x50#').url, alt: @array[3].id, class: 'img-thumbnail')%>       <a href ="/anime/<%=@array[3].id%>">  &nbsp&nbsp&nbsp<%=@array[3].name%></a></P><p><%= link_to image_tag(@array[4].image.thumb('50x50#').url, alt: @array[4].id, class: 'img-thumbnail')%>       <a href ="/anime/<%=@array[4].id%>">  &nbsp&nbsp&nbsp<%=@array[4].name%></a></P><p><%= link_to image_tag(@array[0].image.thumb('50x50#').url, alt: @array[0].id, class: 'img-thumbnail')%>       <a href ="/anime/<%=@array[0].id%>">  &nbsp&nbsp&nbsp<%=@array[0].name%></a></P></div></div>
    <div class="boxgeek">  <div class="alea"><h2> 5 Jeux aleatoire</h2><p><%= link_to image_tag(@jeuxarray[1].image.thumb('50x50#').url, alt: @jeuxarray[1].id, class: 'img-thumbnail')%>       <a href ="/jeux/<%=@jeuxarray[1].id%>">  &nbsp&nbsp&nbsp<%=@jeuxarray[1].name%></a></P><p><%= link_to image_tag(@jeuxarray[2].image.thumb('50x50#').url, alt: @jeuxarray[2].id, class: 'img-thumbnail')%>       <a href ="/jeux/<%=@jeuxarray[2].id%>">  &nbsp&nbsp&nbsp<%=@jeuxarray[2].name%></a></P><p><%= link_to image_tag(@jeuxarray[3].image.thumb('50x50#').url, alt: @jeuxarray[3].id, class: 'img-thumbnail')%>       <a href ="/jeux/<%=@jeuxarray[3].id%>">  &nbsp&nbsp&nbsp<%=@jeuxarray[3].name%></a></P><p><%= link_to image_tag(@jeuxarray[4].image.thumb('50x50#').url, alt: @jeuxarray[4].id, class: 'img-thumbnail')%>       <a href ="/jeux/<%=@jeuxarray[4].id%>">  &nbsp&nbsp&nbsp<%=@jeuxarray[4].name%></a></P><p><%= link_to image_tag(@jeuxarray[0].image.thumb('50x50#').url, alt: @jeuxarray[0].id, class: 'img-thumbnail')%>       <a href ="/jeux/<%=@jeuxarray[0].id%>">  &nbsp&nbsp&nbsp<%=@jeuxarray[0].name%></a></P></div></div>
    <div class="boxgeek">  <div class="alea"><h2> 5 Serie aleatoire</h2><p><%= link_to image_tag(@seriearray[1].image.thumb('50x50#').url, alt: @seriearray[1].id, class: 'img-thumbnail')%>       <a href ="/serie/<%=@seriearray[1].id%>">  &nbsp&nbsp&nbsp<%=@seriearray[1].name%></a></P><p><%= link_to image_tag(@seriearray[2].image.thumb('50x50#').url, alt: @seriearray[2].id, class: 'img-thumbnail')%>       <a href ="/serie/<%=@seriearray[2].id%>">  &nbsp&nbsp&nbsp<%=@seriearray[2].name%></a></P><p><%= link_to image_tag(@seriearray[3].image.thumb('50x50#').url, alt: @seriearray[3].id, class: 'img-thumbnail')%>       <a href ="/serie/<%=@seriearray[3].id%>">  &nbsp&nbsp&nbsp<%=@seriearray[3].name%></a></P><p><%= link_to image_tag(@seriearray[4].image.thumb('50x50#').url, alt: @seriearray[4].id, class: 'img-thumbnail')%>       <a href ="/serie/<%=@seriearray[4].id%>">  &nbsp&nbsp&nbsp<%=@seriearray[4].name%></a></P><p><%= link_to image_tag(@seriearray[0].image.thumb('50x50#').url, alt: @seriearray[0].id, class: 'img-thumbnail')%>       <a href ="/serie/<%=@seriearray[0].id%>">  &nbsp&nbsp&nbsp<%=@seriearray[0].name%></a></P></div></div>
    </div><div class="box ">

    <div class="tmess">
      <div class="">
        <div class="amis">

        <div class "panel-head2">

          <h2>Contacts</h2>   </div> <ul><%@mesamis.each do |user|%>

              <%a = DateTime.now.utc - user.lasttime%>
              <%ud =(a /60).to_i %>

              <li><%= link_to image_tag(Photo.where(user: user.id).last.image.thumb('60x60#').url, alt: user.id, class: 'img-thumbnail')%> <%= link_to user.pseudo, conversations_path(user_id: user), remote: true, method: :post %> <%if ud <= 5 %><span class="online" >en ligne</span><%else%><%=ud%>min<%end%></li>
            <% end %>
          </ul>

     </div>
        <ul id="conversations-list">
          <% @conversations.each do |conversation| %>
          <div class="tmess">
            <%= render 'conversations/conversation', conversation: conversation, user: current_user %>
          </div>
          <% end %>
        </ul>




        </div>
            </div>
                </div>





  <div class="box">
<div class=" cont">




   <%tweet = @t%>
   <div class="tweets">
<%ida = User.where(pseudo: @t.auteur).last.id%>

   <div class="tuser"><%= link_to image_tag(Photo.where(user: User.where(pseudo: @t.auteur).last.id).last.image.thumb('60x60#').url, alt: "userimage", class: 'img-thumbnail')%> <p><a href ="/users/profil/<%=ida%>"><%=tweet.auteur%></a>  <span class="ttweet"><%=tweet.tilte%></span></P></div> <%=tweet.created_at%></p>
   <%= form_for @tweet , url: {action: 'update'} do |f| %>
       <p class ="ttext">   <%= f.trix_editor  :content%></p>
       <%=f.label :Changer_l_image%>
       <%= f.file_field  :image  %>
       <%if tweet.image_uid !=nil%>
       <%= link_to image_tag(tweet.image.thumb('850x531#').url, alt: tweet.auteur, class: 'img-thumbnail'),
                 tweet.image.url, target: '_blank' %>
                   <%end%>
                   <div class="actions ">
                     <%= f.submit "Mettre à jour"%>
                   </div>


            <% end %>
       <div class="boxb">

         <%if tweet.ido == nil%>
         <%aime = tweet.aime%>
         <%else%>
         <%aime = Tweet.find(tweet.ido).aime%>
         <%end%>

   </div>

   </div>





   </div>

          </div>



</div>

app/views/tweets/lesseries.html.erb
<div class=" conten">
  <div class="box"><div class="boxgeek"> <div class="alea"><h2> 5 Animer aleatoire</h2><p><%= link_to image_tag(@array[1].image.thumb('50x50#').url, alt: @array[1].id, class: 'img-thumbnail')%>       <a href ="/anime/<%=@array[1].id%>">  &nbsp&nbsp&nbsp<%=@array[1].name%></a></P><p><%= link_to image_tag(@array[2].image.thumb('50x50#').url, alt: @array[2].id, class: 'img-thumbnail')%>       <a href ="/anime/<%=@array[2].id%>">  &nbsp&nbsp&nbsp<%=@array[2].name%></a></P><p><%= link_to image_tag(@array[3].image.thumb('50x50#').url, alt: @array[3].id, class: 'img-thumbnail')%>       <a href ="/anime/<%=@array[3].id%>">  &nbsp&nbsp&nbsp<%=@array[3].name%></a></P><p><%= link_to image_tag(@array[4].image.thumb('50x50#').url, alt: @array[4].id, class: 'img-thumbnail')%>       <a href ="/anime/<%=@array[4].id%>">  &nbsp&nbsp&nbsp<%=@array[4].name%></a></P><p><%= link_to image_tag(@array[0].image.thumb('50x50#').url, alt: @array[0].id, class: 'img-thumbnail')%>       <a href ="/anime/<%=@array[0].id%>">  &nbsp&nbsp&nbsp<%=@array[0].name%></a></P></div></div>
  <div class="boxgeek">  <div class="alea"><h2> 5 Jeux aleatoire</h2><p><%= link_to image_tag(@jeuxarray[1].image.thumb('50x50#').url, alt: @jeuxarray[1].id, class: 'img-thumbnail')%>       <a href ="/jeux/<%=@jeuxarray[1].id%>">  &nbsp&nbsp&nbsp<%=@jeuxarray[1].name%></a></P><p><%= link_to image_tag(@jeuxarray[2].image.thumb('50x50#').url, alt: @jeuxarray[2].id, class: 'img-thumbnail')%>       <a href ="/jeux/<%=@jeuxarray[2].id%>">  &nbsp&nbsp&nbsp<%=@jeuxarray[2].name%></a></P><p><%= link_to image_tag(@jeuxarray[3].image.thumb('50x50#').url, alt: @jeuxarray[3].id, class: 'img-thumbnail')%>       <a href ="/jeux/<%=@jeuxarray[3].id%>">  &nbsp&nbsp&nbsp<%=@jeuxarray[3].name%></a></P><p><%= link_to image_tag(@jeuxarray[4].image.thumb('50x50#').url, alt: @jeuxarray[4].id, class: 'img-thumbnail')%>       <a href ="/jeux/<%=@jeuxarray[4].id%>">  &nbsp&nbsp&nbsp<%=@jeuxarray[4].name%></a></P><p><%= link_to image_tag(@jeuxarray[0].image.thumb('50x50#').url, alt: @jeuxarray[0].id, class: 'img-thumbnail')%>       <a href ="/jeux/<%=@jeuxarray[0].id%>">  &nbsp&nbsp&nbsp<%=@jeuxarray[0].name%></a></P></div></div>
  <div class="boxgeek">  <div class="alea"><h2> 5 Serie aleatoire</h2><p><%= link_to image_tag(@seriearray[1].image.thumb('50x50#').url, alt: @seriearray[1].id, class: 'img-thumbnail')%>       <a href ="/serie/<%=@seriearray[1].id%>">  &nbsp&nbsp&nbsp<%=@seriearray[1].name%></a></P><p><%= link_to image_tag(@seriearray[2].image.thumb('50x50#').url, alt: @seriearray[2].id, class: 'img-thumbnail')%>       <a href ="/serie/<%=@seriearray[2].id%>">  &nbsp&nbsp&nbsp<%=@seriearray[2].name%></a></P><p><%= link_to image_tag(@seriearray[3].image.thumb('50x50#').url, alt: @seriearray[3].id, class: 'img-thumbnail')%>       <a href ="/serie/<%=@seriearray[3].id%>">  &nbsp&nbsp&nbsp<%=@seriearray[3].name%></a></P><p><%= link_to image_tag(@seriearray[4].image.thumb('50x50#').url, alt: @seriearray[4].id, class: 'img-thumbnail')%>       <a href ="/serie/<%=@seriearray[4].id%>">  &nbsp&nbsp&nbsp<%=@seriearray[4].name%></a></P><p><%= link_to image_tag(@seriearray[0].image.thumb('50x50#').url, alt: @seriearray[0].id, class: 'img-thumbnail')%>       <a href ="/serie/<%=@seriearray[0].id%>">  &nbsp&nbsp&nbsp<%=@seriearray[0].name%></a></P></div></div>
  </div>
  <div class="box ">

  <div class="tmess">
    <div class="">
      <div class="amis">

      <div class "panel-head2">

        <h2>Contacts</h2>   </div> <ul><%@mesamis.each do |user|%>

            <%a = DateTime.now.utc - user.lasttime%>
            <%ud =(a /60).to_i %>

            <li><%= link_to image_tag(Photo.where(user: user.id).last.image.thumb('60x60#').url, alt: user.id, class: 'img-thumbnail')%> <%= link_to user.pseudo, conversations_path(user_id: user), remote: true, method: :post %> <%if ud <= 5 %><span class="online" >en ligne</span><%else%><%=ud%>min<%end%></li>
          <% end %>
        </ul>

   </div>
      <ul id="conversations-list">
        <% @conversations.each do |conversation| %>
        <div class="tmess">
          <%= render 'conversations/conversation', conversation: conversation, user: current_user %>
        </div>
        <% end %>
      </ul>




      </div>
          </div>
              </div>


<div class="box">

  <div class=" cont">

    <%@resul=Serie.all.sort{ |a, b| a.name <=> b.name }.reverse %>


            <%@resul.each do |e|%> <%if e.image !=nil%> <div class="tweets "><div class="amisc"><%= link_to image_tag(e.image.thumb('70x70#').url, alt: e.id, class: 'img-thumbnail')%>       <a href ="/serie/<%=e.id%>">  &nbsp&nbsp&nbsp<%=e.name%></a>
                <%list =Seriegenre.where(serie_id: e.id)%>
              &nbsp  &nbsp  &nbsp  &nbsp <span> Genre : </span> <%list.each do |i|%> <%=i.categorieserie.name%> <%end%> </P>



                </div></div><%end%>
        <%end%>

        <div class="anime ">
          <ul class="userbox">
            <li><a href="/seriet">Accueil</A> </li>
              <li><a href="/lesseries">Les Series</A> </li>
              <li><a href="/srechegenre">Recherche par genre</A> </li>
            <li><a href="/aleatoires">Serie aléatoire </A> </li>
                <li><a href="/addserie">Ajouter une serie </A> </li>


          </ul>
        <div class="userbox">
          <%= form_tag "/sreche", method: "post" do %>
            <p><input class="rechecher " type="string" name="rechecher"  placeholder="ex: serie "/>

            <input  type="submit" class="submit2" value="rechecher"/></p>
            <%end%>
                      </div>
                        </div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>